version: 0.0
os: linux

files:
  - source: application-code/web-tier
    destination: /var/www/react-app
  - source: application-code/app-tier
    destination: /var/www/backend-app
  - source: application-code/web-tier/nginx.conf
    destination: /etc/nginx/nginx.conf
  - source: scripts
    destination: /home/ubuntu/scripts
    
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
