version: 0.0
os: linux

files:
  - source: application-code/web-tier/build
    destination: /var/www/react-app
  - source: application-code/app-tier
    destination: /var/www/app
  - source: application-code/web-tier/nginx.conf
    destination: /etc/nginx/sites-available/react-backend

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
